services:
  data-teman-mysql:
    image: mysql:8.0
    container_name: data-teman-mysql
    env_file:
    - .env
    ports:
      - 3307:3306
    volumes:
      - data-teman-mysql-data:/var/lib/mysql
  data-teman-redis:
    image: redis:8
    container_name: data-teman-redis
    ports:
    - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
    - data-teman-redis-data:/data
    env_file:
    - .env

volumes:
  data-teman-mysql-data:
  data-teman-redis-data: